### ISSUE TITLE
Data collection freezes while driving

### ISSUE THREAD

**Issue by TechnicalLee** [obdgeek/obd-record#13]
![IMG_1712](https://user-images.githubusercontent.com/76839682/230688711-dbaf68b7-6537-48e7-bca7-1ad607452f57.png)

Screenshot taken after driving 30 miles and while in park. Data stopped updating after 8 miles, no trip data saved. Commands sent were still increasing, but park gear was not registered.

**Comment by obdgeek** [comment]
Not much for me to act on, I did 135+ trips in the last 30 days and I haven’t had problems but it could be related to one of the known issues with cell dropouts or scan tool disconnects. I have yet to get a crash report from Apple so it’s not like I have that to look at.

If you are auto connecting, I would disable that option since a scan tool disconnect might automatically reconnect with some zombie threads running. It’s going to leave you in an undesirable state, I always tap connect when I get in the vehicle and launch OBD Record to make sure I know I’m starting fresh. 

Just going to have to wait for a build that includes logging so I have some idea of what the app saw before it failed to operate correctly. Hopefully won’t be too long, today I successfully recorded a DCFC session at Electrify America, so that feature will go out in the next build

**Comment by TechnicalLee** [comment]
I manually connected the OBDLink when I got in the car and started the app. Set phone down and didn't touch it while driving. Got some CarPlay text messages so maybe that screwed it up. It seems like the problem is the connection to the adapter gets messed up somehow but the program doesn't notice the lack of replies. Could you potentially add a watchdog that looks at recent data being received? If no recent data is being received, auto disconnect and reconnect from the adapter or start the handshake with the car again?

**Comment by obdgeek** [comment]
I use CarPlay or have it launch when a Message is received without problems but I don't launch the Map app while in CarPlay since that would double the location workload for the device.  Also there are a range of devices going back to the iPhone 8 that could be used and may be marginal while I use an iPhone 14 Pro for testing.

For now you just have live with the occasional issue until I work through my list of action items that will either fix these issues (known BT connect/disconnect issues and living with the loss of cell service) or will shed some light on them (implementing detailed logging).

**Comment by obdgeek** [comment]
FYI, in least week I had one AC charge  and one trip get stuck so the problem is real (but relatively rare for me).  But until there are useful logs (which are actively being worked on) to sort it out there is nothing to act on.
